# Generated by Django 3.0.5 on 2020-05-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackformapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Employee',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Product',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Recommendable',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Service',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='Value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='total',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
