# Generated by Django 3.0.5 on 2020-05-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackformapp', '0002_auto_20200504_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='company',
        ),
    ]
